name: HTML Quality Check

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to scan"
        required: true

      repo:
        description: "Repositorio"  
        required: true

jobs:
  scan_html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repository (where the Actions script is located)
        uses: actions/checkout@v3

      - name: Clone the repository to be scanned
        run: |
          git clone --branch ${{ github.event.inputs.branch }} https://github.com/$ mvthivs23/${{ github.event.inputs.repo }}.git target_repo
          ls -la target_repo

      - name: Run HTML Quality Check
        run: |
          chmod +x ./html_quality_check.sh
          ./html_quality_check.sh ./target_repo